const schoolsCatalog = [
  {
    estado: "CDMX",
    escuela: "Instituto Miguel Angel",
    escolaridad: ["Primaria", "Secundaria", "Preparatoria"],
    img:"img/6. Logos/IMA.jpg",
    images: [
      "uniformes/Imagenes más pequeñas/0. Chamarra deportiva.jpg",
      "uniformes/Imagenes más pequeñas/0.1 Chamarra deportiva 2.jpg",
      "uniformes/Imagenes más pequeñas/0.3 Pantalón de Pants.jpg",
      "uniformes/Imagenes más pequeñas/0.4 Pantalón de Pants 2.jpg",
      "uniformes/Imagenes más pequeñas/0.5 Playera Polo.jpg",
      "uniformes/Imagenes más pequeñas/0.6 Playera polo 2.jpg",
      "uniformes/Imagenes más pequeñas/0.7 Calceta deportiva.jpg",
      "uniformes/Imagenes más pequeñas/0.8 Agujetas rojas.jpg",
      "uniformes/Imagenes más pequeñas/1. Diario niña primaria.jpg",
      "uniformes/Imagenes más pequeñas/1.1 Jumper.jpg",
      "uniformes/Imagenes más pequeñas/1.2 Juego de puños y cuellos.jpg",
      "uniformes/Imagenes más pequeñas/1.3 Sueter niña.jpg",
      "uniformes/Imagenes más pequeñas/1.4 Zapato.jpg",
      "uniformes/Imagenes más pequeñas/1.5 Calcetas azules.jpg",
      "uniformes/Imagenes más pequeñas/1.6 Calceta blanca.jpg",
      "uniformes/Imagenes más pequeñas/1.7 Licras.jpg",
      "uniformes/Imagenes más pequeñas/1.8 Listón de gala niña.jpg",
      "uniformes/Imagenes más pequeñas/2. Diario niña prepa.jpg",
      "uniformes/Imagenes más pequeñas/2.1 Blusa prepa.jpg",
      "uniformes/Imagenes más pequeñas/2.2 Chaleco.jpg",
      "uniformes/Imagenes más pequeñas/2.3 Falda prepa.jpg",
      "uniformes/Imagenes más pequeñas/2.4 Mocasin.jpg",
      "uniformes/Imagenes más pequeñas/3. Diario niño.jpg",
      "uniformes/Imagenes más pequeñas/3.1 Camisa.jpg",
      "uniformes/Imagenes más pequeñas/3.2 Corbata.jpg",
      "uniformes/Imagenes más pequeñas/3.3 Corbata lisa.jpg",
      "uniformes/Imagenes más pequeñas/3.4 Sueter niño.jpg",
      "uniformes/Imagenes más pequeñas/3.5 Pantalón de vestir.jpg",
      "uniformes/Imagenes más pequeñas/3.6 Calcetín.jpg",
      "uniformes/Imagenes más pequeñas/4. Bata pintura.jpg",
      "uniformes/Imagenes más pequeñas/4.0 Chamarra impermeable.jpg",
      "uniformes/Imagenes más pequeñas/4.1 Chaleco Capitonado.jpg",
      "uniformes/Imagenes más pequeñas/4.2 Sudadera borrega.jpg",
      "uniformes/Imagenes más pequeñas/4.3 Moño 1.jpg",
      "uniformes/Imagenes más pequeñas/4.4 Moño 2.jpg",
      "uniformes/Imagenes más pequeñas/4.5 Gorra azul.jpg",
      "uniformes/Imagenes más pequeñas/4.6 Gorra roja.jpg",
      "uniformes/Imagenes más pequeñas/4.7 Mallas azules.jpg",
      "uniformes/Imagenes más pequeñas/4.8 Mallas blancas.jpg",
      "uniformes/Imagenes más pequeñas/4.9 Juego botones jumper.jpg",
      "uniformes/Imagenes más pequeñas/4.10 Botones suéter.jpg",
      "uniformes/Imagenes más pequeñas/4.11 Guantes escolta.jpg",
      "uniformes/Imagenes más pequeñas/4.12 Gorro Invierno.jpg",
      "uniformes/Imagenes más pequeñas/4.13 Guantes invierno.jpg"
    ]
  },

  {
    estado: "CDMX",
    escuela: "CEB",
    escolaridad: ["Preparatoria"],
    images: [
      "uniformes/2. CEB/1 chamarra_pants_ceb.jpg",
      "uniformes/2. CEB/2  chamarra_pants_ceb_2.jpg",
      "uniformes/2. CEB/3 pantalon_pants_ceb.jpg",
      "uniformes/2. CEB/4 chamarra_pants_ceb_3.jpg",
      "uniformes/2. CEB/5 deportes_ceb.jpg",
      "uniformes/2. CEB/6 playera_dep_blanca_ceb.jpg",
      "uniformes/2. CEB/7 playera_dep_blanca_ceb_2.jpg",
      "uniformes/2. CEB/8 playera_dep_azul_ceb.jpg",
      "uniformes/2. CEB/9 playera_dep_azul_ceb_2.jpg",
      "uniformes/2. CEB/10 playera_dep_blanca_ceb_4.jpg",
      "uniformes/2. CEB/11 playera_dep_azul_3.jpg",
      "uniformes/2. CEB/12 playera_ceb.jpg",
      "uniformes/2. CEB/13 playera_ceb_2.jpg",
      "uniformes/2. CEB/13.1 playera_ceb_3.jpg",
      "uniformes/2. CEB/14 falda_ceb.jpg",
      "uniformes/2. CEB/15 falda_ceb_2.jpg",
      "uniformes/2. CEB/16 falda_ceb_3.jpg",
      "uniformes/2. CEB/16.1 sueter_abierto_ceb.jpg",
      "uniformes/2. CEB/17 diario_nina_ceb.jpg",
      "uniformes/2. CEB/18 pantalon_ceb.jpg",
      "uniformes/2. CEB/19 sueter_cerrado_ceb.jpg",
      "uniformes/2. CEB/20 pantalon_ceb_2.jpg",
      "uniformes/2. CEB/21 diario_nino_ceb.jpg"
    ]
  },

  {
    estado: "CDMX",
    escuela: "Colegio Belfort",
    escolaridad: ["Primaria", "Secundaria", "Preparatoria"],
    images: [
      "img/galeria/Belfort/blusa_belfort.jpg",
      "img/galeria/Belfort/2. jumper_belfort.jpg",
      "img/galeria/Belfort/camisa_belfort_primaria.jpg",
      "img/galeria/Belfort/camisa_belfort.jpg",
      "img/galeria/Belfort/corbata_secundaria_belfort.jpg",
      "img/galeria/Belfort/corbatin_secundaria_belfort.jpg",
      "img/galeria/Belfort/calceltas_belfort.jpg",
      "img/galeria/Belfort/calceta_belfort.jpg",
      "img/galeria/Belfort/mallas_belfort.jpg",
      "img/galeria/Belfort/bata_azul_belfort_2.jpg",
      "img/galeria/Belfort/bata_azul_belfort.jpg",
      "img/galeria/Belfort/bata_laboratoio_belfort.jpg",
      "img/galeria/Belfort/bufanda_belfort.jpg",
      "img/galeria/Belfort/dep - pantalon_pants_belfort.jpg",
      "img/galeria/Belfort/playera_deportiva_azul.jpg",
      "img/galeria/Belfort/playera_deportiva_blanca.jpg",
      "img/galeria/Belfort/chamarra_pants_belfort.jpg",
      "img/galeria/Belfort/chamarra_pants_belfort_2.jpg",
      "img/galeria/Belfort/chamarra_imp_belfort.jpg",
      "img/galeria/Belfort/chamarra_imp_belfort_2.jpg",
      "img/galeria/Belfort/sueter_belfort.jpg",
      "img/galeria/Belfort/4. sueter_belfort.jpg",
      "img/galeria/Belfort/3. sueter_belfort_2.jpg",
      "img/galeria/Belfort/chaleco_capitonado_belfort.jpg"
    ]
  },


  {
    estado: "CDMX",
    escuela: "Colegio Morelos",
    escolaridad: ["Primaria", "Secundaria", "Preparatoria"],
    images: [
      "uniformes/4. Morelos/Camisa manga larga corbatin morelos.jpg",
      "uniformes/4. Morelos/Camisa manga larga morelos.jpg",
      "uniformes/4. Morelos/Camisa morelos.jpg",
      "uniformes/4. Morelos/Capa estudiantina atras.jpg",
      "uniformes/4. Morelos/Capa estudiantina.jpg",
      "uniformes/4. Morelos/chaleco_morelos.jpg",
      "uniformes/4. Morelos/chaleco_morelos_2.jpg",
      "uniformes/4. Morelos/Chamarra de pants 1.jpg",
      "uniformes/4. Morelos/Chamarra de pants 2.jpg",
      "uniformes/4. Morelos/falda_morelos.jpg",
      "uniformes/4. Morelos/falda_morelos_2.jpg",
      "uniformes/4. Morelos/falda_morelos_cuadros.jpg",
      "uniformes/4. Morelos/falda_morelos_cuadros_atras.jpg",
      "uniformes/4. Morelos/Moño.jpg",
      "uniformes/4. Morelos/Pantalon de pants.jpg",
      "uniformes/4. Morelos/pantalon_morelos.jpg",
      "uniformes/4. Morelos/Playera polo.jpg",
      "uniformes/4. Morelos/Playera ruso.jpg",
      "uniformes/4. Morelos/Saco Gala niña.jpg",
      "uniformes/4. Morelos/Saco Gala.jpg",
      "uniformes/4. Morelos/Shorts morelos.jpg",
      "uniformes/4. Morelos/Sueter cerrado morelos.jpg",
      "uniformes/4. Morelos/sueter_morelos.jpg",
      "uniformes/4. Morelos/sueter_morelos_2.jpg",
      "uniformes/4. Morelos/Uniforme niña.jpg"
    ]

  },

  {
    estado: "CDMX",
    escuela: "Kids Center",
    escolaridad: ["Maternal", "Prescolar"],
    images: [
      "uniformes/Kids_Center/1 chamarra_pants_kid_s_center.jpg",
      "uniformes/Kids_Center/2 chamarra_pants_kid_s_center_2.jpg",
      "uniformes/Kids_Center/3 pantalon_pants_kid_s_center.jpg",
      "uniformes/Kids_Center/4 Camisa Kid_s center.jpg",
      "uniformes/Kids_Center/5 chaleco_kid_s_center.jpg",
      "uniformes/Kids_Center/6 jumper_kid_s_center.jpg",
      "uniformes/Kids_Center/7 jumper_kid_s_center_2.jpg",
      "uniformes/Kids_Center/8 pantalon_kid_s_center.jpg",
      "uniformes/Kids_Center/9 sueter_kid_s_center.jpg"
    ]

  },

  {
    estado: "CDMX",
    escuela: "Universidad Panamericana",
    escolaridad: ["Universidad"],
    images: [
      "uniformes/UP/1 Chaleo UP.jpg",
      "uniformes/UP/Chaleo UP.jpg",
      "uniformes/UP/Chaleo UP atrás.jpg",
      "uniformes/UP/chamarra_pants_up.jpg",
      "uniformes/UP/chamarra_pants_up_2.jpg",
      "uniformes/UP/playera_blanca_up_robotica.jpg",
      "uniformes/UP/playera_blanca_up_robotica_2.jpg",
      "uniformes/UP/playera_mangalarga_up.jpg",
      "uniformes/UP/playera_mangalarga_up_2.jpg",
      "uniformes/UP/playera_up_robotica.jpg",
      "uniformes/UP/playera_up_robotica_2.jpg",
      "uniformes/UP/polo_blanca_up_robotica.jpg",
      "uniformes/UP/polo_blanca_up_robotica_2.jpg",
      "uniformes/UP/short_pants_up.jpg",
      "uniformes/UP/short_up.jpg"
    ]
  }
];
